import type { Metadata } from "next";
import "@/styles/globals.css";
import localFont from "next/font/local";
import AOSInit from "@/utils/aos";
import Footer from "@/components/modules/Footer/Footer";
// pages/_app.js (or _app.tsx)
import "tailwindcss/tailwind.css"; // Make sure the path is correct

const myFont = localFont({ src: "./../../public/fonts/IRANSansFaNum.ttf" });
export const metadata: Metadata = {
  title: "قهوه کینگ | صفحه اصلی",
  description: "Generated by create next app",
  icons: "/images/about-icon-1.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={myFont.className}>
        <AOSInit />
        {children}
        <Footer />
      </body>
    </html>
  );
}
